### ISSUE TITLE
Bug: Does not pack alpha 

### ISSUE THREAD

**Issue by LaserYGD** [JMargevics/Unity-Texture-Packer#1]
This application doesn't seem to pack a texture to alpha when requested to, all the other channels (R/G/B) work correctly, Unfortunately this is a massive issue since most people use texture packers for the alpha channel.

**Comment by JMargevics** [comment]
Hello! Apologies for a super late reply. Finally took some time recently to rework this utility. Now I pass everything through a simple fragment shader vs doing everything on CPU. Rescaling as a result is also much faster and done on hardware. I have tested packing alpha channels specifically and all seems to work correctly now.
